// ============================================
// globe-data.js — Place metadata for globe pins
// No fake reviews here. Real reviews are fetched
// from /api/scrape which reads from cache/ or runs
// the actual scraper pipeline.
// ============================================

export const PLACES = [
    {
        id: 'cafe-de-flore',
        name: 'Café de Flore',
        city: 'Paris',
        country: 'France',
        countryCode: 'fr',
        coords: [48.8566, 2.3333],
        category: 'Historic café',
        emoji: '☕',
        mapsUrl: 'https://maps.app.goo.gl/CCGmfPudoLzPoK2a7',
        searchQuery: 'Café de Flore Paris',
        tagline: 'Where Sartre wrote and everyone pretends to be French enough to belong.',
    },
    {
        id: 'ichiran-shibuya',
        name: 'Ichiran Ramen',
        city: 'Tokyo',
        country: 'Japan',
        countryCode: 'jp',
        coords: [35.6595, 139.7004],
        category: 'Ramen',
        emoji: '🍜',
        mapsUrl: 'https://maps.app.goo.gl/YOUR_SHIBUYA_URL',
        searchQuery: 'Ichiran Ramen Shibuya Tokyo',
        tagline: 'Solo booth, single bowl, total focus.',
    },
    {
        id: 'blue-bottle-oakland',
        name: 'Blue Bottle Coffee',
        city: 'Oakland',
        country: 'USA',
        countryCode: 'us',
        coords: [37.8044, -122.2711],
        category: 'Specialty coffee',
        emoji: '☕',
        mapsUrl: 'https://maps.app.goo.gl/YOUR_BB_OAKLAND_URL',
        searchQuery: 'Blue Bottle Coffee Oakland',
        tagline: 'Pour-over precision in a converted warehouse.',
    },
    {
        id: 'dishoom-shoreditch',
        name: 'Dishoom',
        city: 'London',
        country: 'United Kingdom',
        countryCode: 'gb',
        coords: [51.5253, -0.0769],
        category: 'Indian restaurant',
        emoji: '🍛',
        mapsUrl: 'https://maps.app.goo.gl/YOUR_DISHOOM_URL',
        searchQuery: 'Dishoom Shoreditch London',
        tagline: 'Bombay café nostalgia, properly executed.',
    },
    {
        id: 'el-celler-de-can-roca',
        name: 'El Celler de Can Roca',
        city: 'Girona',
        country: 'Spain',
        countryCode: 'es',
        coords: [41.9794, 2.8061],
        category: 'Fine dining',
        emoji: '🍽️',
        mapsUrl: 'https://maps.app.goo.gl/YOUR_CANROCA_URL',
        searchQuery: 'El Celler de Can Roca Girona',
        tagline: 'Three brothers, one of the world\'s best meals.',
    },
    {
        id: 'tim-ho-wan',
        name: 'Tim Ho Wan',
        city: 'Hong Kong',
        country: 'Hong Kong',
        countryCode: 'hk',
        coords: [22.2783, 114.1747],
        category: 'Dim sum',
        emoji: '🥟',
        mapsUrl: 'https://maps.app.goo.gl/YOUR_TIMHOWAN_URL',
        searchQuery: 'Tim Ho Wan Hong Kong',
        tagline: 'Cheapest Michelin star in the world.',
    },
    {
        id: 'gymkhana',
        name: 'Gymkhana',
        city: 'New Delhi',
        country: 'India',
        countryCode: 'in',
        coords: [28.5984, 77.2273],
        category: 'Indian fine dining',
        emoji: '🍛',
        mapsUrl: 'https://maps.app.goo.gl/YOUR_GYMKHANA_URL',
        searchQuery: 'Gymkhana New Delhi',
        tagline: 'Colonial India reimagined with a Michelin star.',
    },
    {
        id: 'septime',
        name: 'Septime',
        city: 'Paris',
        country: 'France',
        countryCode: 'fr',
        coords: [48.8530, 2.3789],
        category: 'Bistro',
        emoji: '🍷',
        mapsUrl: 'https://maps.app.goo.gl/YOUR_SEPTIME_URL',
        searchQuery: 'Septime Paris',
        tagline: 'The reservation that broke Paris.',
    },
    {
        id: 'pujol',
        name: 'Pujol',
        city: 'Mexico City',
        country: 'Mexico',
        countryCode: 'mx',
        coords: [19.4326, -99.1932],
        category: 'Modern Mexican',
        emoji: '🌽',
        mapsUrl: 'https://maps.app.goo.gl/YOUR_PUJOL_URL',
        searchQuery: 'Pujol Mexico City Polanco',
        tagline: 'Mole madre aged 1,500+ days.',
    },
    {
        id: 'attica',
        name: 'Attica',
        city: 'Melbourne',
        country: 'Australia',
        countryCode: 'au',
        coords: [-37.8534, 145.0225],
        category: 'Modern Australian',
        emoji: '🦘',
        mapsUrl: 'https://maps.app.goo.gl/YOUR_ATTICA_URL',
        searchQuery: 'Attica Ripponlea Melbourne',
        tagline: 'Australian ingredients, treated with rigor.',
    },
];